name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: mlops-rg
  AKS_CLUSTER_NAME: mlops-aks-cluster
  ACR_NAME: mlopsacregistry123
  IMAGE_NAME: sentiment-api

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        pip install -r ml/requirements.txt

    - name: Run Tests
      run: |
        python -m unittest discover ml/tests || echo "No tests for now"

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build Docker Image
      run: |
        az acr login --name ${{ env.ACR_NAME }}
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest -f app/Dockerfile .
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
